### ISSUE TITLE
建議新增可顯示更詳細錯誤訊息的 Gems 方便 Debug

### ISSUE THREAD

**Issue by ChouAndy** [hiroshiyui/trellis#11]
https://github.com/charliesome/better_errors

https://github.com/banister/binding_of_caller

https://github.com/qqshfox/meta_request

**Comment by hiroshiyui** [comment]
@ChouAndy 這些工具看起來不錯，就直接加上去？

**Comment by HanaHsu** [comment]
:+1::+1::+1:
