### ISSUE TITLE
新增 Gherkin 物件 MVC

### ISSUE THREAD

**Issue by hiroshiyui** [hiroshiyui/trellis#7]

**Comment by hiroshiyui** [comment]
考慮 Gherkin content 在資料庫儲存的簡便性，我想還是存成 text 然後用 Travis 建議的方式做 tidying, indenting。

**Comment by hiroshiyui** [comment]
對了，如此一來就不需要綁 PostgreSQL :sweat_smile:

**Comment by ChouAndy** [comment]
因為 Heroku 只免費支援 PostgreSQL，所以，就不改 database 的種類，另外因為還沒有確認 gherkin code 的輸入及編輯方式，所以目前只完成登入後可以第一次新增 Gherkin 的 Feature title 和第一筆 Feature code，然後查看個別 Gherkin 可以在該頁面新增累加 Feature code，先呈現簡單的UI，code 按照時間 最新到最舊排列。
model 部分 則由 Gherkin 管理 Feature title，Feature 管理 Feature 的多種 codes，並記錄使用者 ID

**Comment by hiroshiyui** [comment]
@ChouAndy Gherkin code 的輸入及編輯方式，照我目前的規劃，會讓使用者在一個 textarea input 裡輸入、編輯，採取一般 IDE 的 auto-complete 方式輔助輸入，譬如當使用者輸入 "fe" 時自動彈入 auto-complete 列表 "Feature" 供其參考選用。不曉得這樣有沒有解答到你的問題？

**Comment by ChouAndy** [comment]
了解 我把 crud 都先弄出來 在持續增加功能

**Comment by hiroshiyui** [comment]
感謝！ :+1:
